package cryptoutil

import (
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha1"
	"encoding/base32"
	"encoding/binary"
	"errors"
	"math"
	"math/big"
	"strconv"
	"strings"
	"time"
)

type OtpGenerator struct {
	serviceName string // required for totp uri generation
	otpLimit    *big.Int
	otpLen      int
	totp        struct {
		length        int
		secretKeySize int
	}
}

func NewOtpGenerator(serviceName string, otpLength, totpLen, totpKeyLen int) OtpGenerator {
	return OtpGenerator{
		serviceName: serviceName,
		otpLimit:    big.NewInt(int64(math.Pow(10, float64(otpLength)))),
		otpLen:      otpLength,
		totp: struct {
			length        int
			secretKeySize int
		}{totpLen, totpKeyLen},
	}
}

// pads the code with the totalLen amount of "0"
func padLeftWithZeros(code int, totalLen int) string {
	s := strconv.Itoa(code)
	return strings.Repeat("0", totalLen-len(s)) + s
}

func (og OtpGenerator) Generate() string {
	num, _ := rand.Int(rand.Reader, og.otpLimit)
	return padLeftWithZeros(int(num.Int64()), og.otpLen)
}

var ErrInvalidSecretKey = errors.New("cryptoutil: invalid secret key")

// Generates a 6 digit time based otp with the given secret key
//
// possible errors are only [ErrInvalidSecretKey] which occurs if the key cannot be decoded
func (og OtpGenerator) GenerateTOTP(secret string) (string, error) {
	secret = strings.ToUpper(strings.TrimSpace(secret))
	key, err := base32.StdEncoding.WithPadding(base32.NoPadding).DecodeString(secret)
	if err != nil {
		return "", ErrInvalidSecretKey
	}

	epoch := time.Now().Unix()
	timeStep := epoch / 30

	buf := make([]byte, 8)
	binary.BigEndian.PutUint64(buf, uint64(timeStep))

	mac := hmac.New(sha1.New, key)
	mac.Write(buf)
	hash := mac.Sum(nil)
	// the below code, i don't understand anything at all, this was generated by GPT, disclaimer. the above i still understand a bit.
	offset := hash[len(hash)-1] & 0xf
	binaryCode := (int32(hash[offset])&0x7f)<<24 |
		(int32(hash[offset+1])&0xff)<<16 |
		(int32(hash[offset+2])&0xff)<<8 |
		(int32(hash[offset+3]) & 0xff)

	mod := int32(math.Pow10(og.totp.length))
	code := binaryCode % mod

	return padLeftWithZeros(int(code), og.totp.length), nil
}

func (og OtpGenerator) SetupTOTP(userIdentifier string) (secretKey string, uri string) {
	keyBytes := make([]byte, og.totp.secretKeySize)
	rand.Read(keyBytes)
	secretKey = strings.ToUpper(base32.StdEncoding.WithPadding(base32.NoPadding).EncodeToString(keyBytes))
	uri = "otpauth://totp/" + og.serviceName +
		":" + userIdentifier +
		"?secret=" + secretKey +
		"&issuer=" + og.serviceName +
		"&digits=" + strconv.Itoa(og.totp.length)
	return
}
